name: ci
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Build React App
        run: yarn build 
